FROM node:alpine
WORKDIR /app
COPY ./package*.json ./
COPY ./pnpm-lock.yaml ./
RUN npm install -g pnpm@8.7.5 && pnpm install
COPY . .
CMD ["npm", "run", "build"]

FROM nginx
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html